services:
  server:
    build:
      context: .
      args:
        MYSQL_USER: laminar
        MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
        MYSQL_URL: mysql://mysql:3306/laminar?useSSL=false&allowPublicKeyRetrieval=true
        EXECUTION_URL: ${LAMINAR_EXECUTION_URL:-host.docker.internal}
        EXECUTION_PORT: ${LAMINAR_EXECUTION_PORT:-5000}
    ports:
      - ${LAMINAR_SERVER_PORT:-8080}:8080
    depends_on:
      - mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: laminar
      MYSQL_USER: laminar
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
    volumes: 
      - laminar-db:/var/lib/mysql

volumes:
  laminar-db:
